version: "3.9"
services:
  auth-db:
    image: postgres:latest
    container_name: auth-db-oms
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis-oms
    ports:
      - "6379:6379"
    networks:
      - backend
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-ui-oms
    ports:
      - "8001:8001" # Web UI Port
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  backend:
    driver: bridge
